### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jim108dev** [typestruck/merochat#163] opened 2020-12-27 14:01 UTC
Hi! I wanted to give it a try.
My OS is Debian 10. Node v15.2.1.
According to https://github.com/melanchat/melanchat/blob/master/CONTRIBUTING.md Setup:
* Run `npm install && spago build`.

Worked after
```
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```
and cloning the `flame_oh_hot_man` branch of Flame in the parent directory.

* Configure PostgreSQL and run [index.sql](src/Server/sql/index.sql) (the user melanchat and databases melanchat and melanchat_test are expected).
I have guessed no password.

* Run `npm run watch` for a hot reloading server at http://localhost:8000.

There seems to be a problem with the Bender installation.

Full console output:
```sh
npm run watch

> melanchat@0.3.5 watch /home/a/github/melanchat
> export DEVELOPMENT=true && nodemon loader/server.js --watch output/Server*/**/* --watch output/Shared*/**/* & webpack --watch --progress --config webpack.development.config.js

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): output/Server*/**/* output/Shared*/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node loader/server.js`
/home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '/home/a/github/melanchat/webpack.development.config.js'
Require stack:
- /home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js
- /home/a/github/melanchat/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (/home/a/github/melanchat/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/a/github/melanchat/node_modules/yargs/yargs.js:576:18)
    at /home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/a/github/melanchat/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/a/github/melanchat/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/a/github/melanchat/node_modules/webpack-cli/bin/cli.js',
    '/home/a/github/melanchat/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! melanchat@0.3.5 watch: `export DEVELOPMENT=true && nodemon loader/server.js --watch output/Server*/**/* --watch output/Shared*/**/* & webpack --watch --progress --config webpack.development.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the melanchat@0.3.5 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/a/.npm/_logs/2020-12-27T13_48_01_742Z-debug.log
a@debian ~/g/m/s/S/sql> node:internal/modules/cjs/loader:1161
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/a/github/melanchat/bender.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1161:18)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/a/github/melanchat/output/Server.Bender/foreign.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14) {
  code: 'ERR_DLOPEN_FAILED'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by easafe** [comment] 2020-12-27 14:31
Hello @jim108dev .,

Thanks for taking the time to write this out, much appreciated!

> According to https://github.com/melanchat/melanchat/blob/master/CONTRIBUTING.md Setup

Yeah, sorry about that, I definitely could do a better job about a smooth getting started. I am currently trying to get it all sorted to launch, but it should be soon to fix it.

> Worked after

My guess about the dev system libraries is that you had to build something from source? Not sure if it is possible pinpoint all of it for all systems.

> and cloning the flame_oh_hot_man branch of Flame in the parent directory

Yeah I am using melanchat to test the big upcoming release of ps-flame, but I will set a specific commit version for the master `package.dhall` to avoid having to do this.

> I have guessed no password.

Yes, trust auth works fine for development. I have yet to set up the production env variables for this one.

> There seems to be a problem with the Bender installation

Loading `bender.node` will crash if it was built for a different system/architecture. I will make it so it is not used by default, and add instructions in case someone wants/needs to build it.

> Error: Cannot find module '/home/a/github/melanchat/webpack.development.config.js' 

Looks like the webpack config file is also missing from git.

**Comment by easafe** [comment] 2020-12-28 04:37
@jim108dev it should be all fixed by 540ec203e84c6fe37ea3e6cb38b046bbc19c5e00.

Could you give it a go again?

**Comment by jim108dev** [comment] 2020-12-28 11:29
Wow, this was quick. 
Leaving password empty didn't work out for me. I have added `, password = Just "melanchat"` to `Database.purs` to get in.

If the window is to small, I did not know how to get out of the chat. Apart from that everything worked great. Thanks a lot.

**Comment by easafe** [comment] 2020-12-28 12:09
> If the window is to small, I did not know how to get out of the chat

Could you expand a bit on this? The desktop layout has a column for contacts and another for suggestion cards/conversations. Mobile shoule have a green arrow on top left when you enter suggestions/chats.

**Comment by jim108dev** [comment] 2020-12-28 14:23
![Screenshot_2020-12-28 Melanchat - Friendly Random Chat](https://user-images.githubusercontent.com/68643861/103220249-141a9680-4920-11eb-9024-3b8a6f520651.png)
That's the window of `http://localhost:8000/im` with Firefox 78. Chrome 83 looks the same.

**Comment by easafe** [comment] 2020-12-28 14:58
That looks quite odd. I can't seem to reproduce it. It looks like the mobile layout, but the top bar and the send button (you can't send messages with enter on mobile) are missing.

**Comment by easafe** [comment] 2021-01-30 07:15
@jim108dev https://melan.chat is now up :D

**Closed as completed by easafe** 2021-01-30 07:15 UTC
